Feat: Updated the Nav merged the both profile and nav into one nav fo…
typehero/typehero pull request #1309
Opened 2023-12-11 14:40 UTC by PraveenShinde3

feat(navbar): Combine profile and navigation menus for mobile view

## Description

## Related Issue
Closes  #1301 

## Motivation and Context
Addresses the issue of having only one menu on the navbar. Merged the profile menu and navigation menu to create a unified and mobile-friendly navigation experience.

## How Has This Been Tested?
Tested on various devices and browsers to ensure consistent behavior and responsiveness.

## Screenshots/Video (if applicable):

For User
![image](https://github.com/typehero/typehero/assets/107350270/31996fe6-39c2-450e-8d3a-a6c4365f1b11)

For Admin
![image](https://github.com/typehero/typehero/assets/107350270/237cc1e3-490a-4303-9df1-880e95939645)

2023-12-12 00:06 UTC, odicho commented
Nice! I think it still feels like something is missing. Are you able to experiment a little with the spacing / see if having a header for each section looks nice? Otherwise, as a first iteration, I think this is definitely an improvement!!

cc: @PickleNik @bautistaaa

2023-12-12 22:21 UTC, bautistaaa commented
this is probably good enough for a first iteration

2023-12-13 05:48 UTC, bautistaaa commented
you need to run `pnpm checks:fix`

2023-12-14 19:25 UTC, aadamw commented on apps/web/src/components/Navigation/nav-link.tsx
> +    <Link href={href} className={mobileView ? 'ml-4 md:hidden' : 'ml-4'}>
q: Why this can't be handled with just CSS?

2023-12-14 21:12 UTC, bautistaaa requested changes

2023-12-14 21:12 UTC, bautistaaa commented on apps/web/src/components/Navigation/index.tsx
> +const session = await auth();
this should be in the context of the component and not global

2023-12-14 21:12 UTC, bautistaaa commented on apps/web/src/components/Navigation/index.tsx
> +const isAdminOrMod = isAdminOrModerator(session);
move inside a component

2023-12-14 23:37 UTC, MichaelG824 commented on apps/web/src/components/Navigation/index.tsx
> +      {session && session.user && (
You can shorten this to use optional chaining e.g session?.user instead.

2023-12-21 17:05 UTC, bautistaaa commented
did you plan on finishing this

2023-12-21 20:12 UTC, bautistaaa commented
made it good enough ™

2023-12-21 20:12 UTC, bautistaaa approved these changes

2023-12-21 20:12 UTC, merged