fix: Improves comments section UI
typehero/typehero pull request #1646
Opened 2024-11-12 14:59 UTC by satishkumarsajjan

## Description

Changed comment component as discussed in the Issue #1615 and #1629 

## Related Issue

Closes #1615 and may be #1629 

## Motivation and Context

UI was out of sync

## How Has This Been Tested?

## Screenshots/Video (if applicable):
[Screencast from 2024-11-12 20-20-12.webm](https://github.com/user-attachments/assets/ff150c9f-b5ca-47ef-bc32-f765e530ca78)

2024-11-13 21:42 UTC, bautistaaa commented
can you run `pnpm checks:fix`

going to get this merged first: https://github.com/typehero/typehero/pull/1640

then we can get yours in!

2024-11-13 21:53 UTC, bautistaaa commented
> can you run `pnpm checks:fix`
> 
> going to get this merged first: #1640
> 
> then we can get yours in!

merged, need to resolve the conflicts

2024-11-14 04:22 UTC, aquibbaig requested changes

2024-11-14 04:22 UTC, aquibbaig commented on apps/web/src/app/challenge/_components/comments/comment.tsx
> +        {/* <div className="flex flex-col items-end gap-2">
let's remove this comment (if not needed)

2024-11-14 04:22 UTC, aquibbaig commented on apps/web/src/app/challenge/_components/comments/comment.tsx
> +      {expanded && seeCollapse && (
do we actually need a new state `collapse` here. I think `expanded` does  something similar.

If we need a new state, shouldn't this condition be `expanded || seeCollapse` to keep the previous behaviour intact ?

2024-11-16 16:15 UTC, closed without merging