Floating Navbar
typehero/typehero pull request #447
Opened 2023-08-26 16:58 UTC by manuarora700

- Floating fixed navbar with a backdrop
- Navbar disappears if the user scrolls down
- Navbar comes back up if the user scrolls up

2023-08-26 18:02 UTC, PickleNik requested changes

2023-08-26 18:02 UTC, PickleNik commented on apps/web/src/components/ui/navigation.tsx
> +        height: useTransform(scrollYBoundedProgressThrottled, [0, 1], [80, 0]),
changing height of the element is not ideal for fps as it triggers a bunch of repaints, I'd `translate-y` it off the screen instead

https://github.com/bautistaaa/typehero/assets/31113245/a8631154-6d79-4258-a7d0-3d770c7036e4

2023-08-26 18:07 UTC, PickleNik commented
overall I like the idea, what if it also was pill-shaped like on https://diagram.com/?

https://github.com/bautistaaa/typehero/assets/31113245/ad2cdad7-69c2-4e0f-baa2-51d08fc15f1b

2023-08-26 18:12 UTC, PickleNik commented on apps/web/src/components/ui/navigation.tsx
> +        height: useTransform(scrollYBoundedProgressThrottled, [0, 1], [80, 0]),
would look even nicer if it's like `scale(0.9)` and `opacity: 0` alongside `translate-y`, none of those trigger repaints either so it shouldn't impact performance

2023-08-28 16:33 UTC, PickleNik commented
sorry i clicked update branch that rebased to main, should not be a big deal, if u got changes just force push and don't worry about it, if u don't just pull before changes, thank you, sorry

2023-09-01 05:08 UTC, bautistaaa commented
is this still being worked on?

2023-09-01 05:10 UTC, manuarora700 commented
yes -- will push an update today @bautistaaa

2023-09-02 19:24 UTC, PickleNik commented
> overall I like the idea, what if it also was pill-shaped like on https://diagram.com/?
> 
>  Screen.Recording.2023-08-26.at.2.06.55.PM.mov

this was just an idea btw, it doesn't have to be in this PR, I'd mainly just fix the bugs with it first and then iterate on design later

2023-09-09 02:41 UTC, bautistaaa commented
this PR seems dead. going to close

2023-09-09 02:41 UTC, closed without merging