feat: implement track detail page
typehero/typehero pull request #594
Opened 2023-09-03 17:08 UTC by DerTimonius

## Description

This PR will implement a design for the `/track/slug` pages. This is currently just a first draft to get some feedback on ideas that could be added:

Current looks:
<img width="1080" alt="image" src="https://github.com/typehero/typehero/assets/103483059/9a747a57-e463-42ea-967e-58512f46187c">

## Ideas

- maybe show the shortDescription on hover
- show trackProgress if enrolled

closes #512

2023-09-04 00:48 UTC, bautistaaa commented
- we can show some indicator of `in progress` for challenges they tried.
- needs a progress meter
- a short description on hover is a nice touch
- track name should be aligned with the list items (i dont think the list items need to be so wide
- enroll bottom should be left aligned under the title

2023-09-06 19:01 UTC, is-it-ayush requested changes
Thank you for the contribution @DerTimonius. Just a tiny change with the `orderId`, otherwise it's all good! 💙✨

2023-09-06 19:59 UTC, DerTimonius commented on apps/web/src/app/[locale]/tracks/_components/track-details.tsx
> +            )
Thanks for the feedback, implemented the change [here](https://github.com/typehero/typehero/commit/f65914160a08c6162e3f6d42d331e7971c19f210)

2023-09-06 20:02 UTC, bautistaaa commented
we left some comments on the preview url. can you see if you can access it? or even request access to it?

2023-09-06 20:10 UTC, DerTimonius commented
@bautistaaa Sorry, can't do either. I only see `Team Access Required You do not have access to comment on this Vercel team’s deployments.` when I try to login

2023-09-08 23:04 UTC, bautistaaa commented
> @bautistaaa Sorry, can't do either. I only see `Team Access Required You do not have access to comment on this Vercel team’s deployments.` when I try to login

let me see if i can get you temp access

2023-09-09 02:43 UTC, bautistaaa commented
can you give me your email. ill add you to the team temporarily so you can see that feedback comments.

2023-09-09 05:15 UTC, DerTimonius commented
timon.jurschitsch@gmail.com

2023-09-09 06:16 UTC, bautistaaa commented
> timon.jurschitsch@gmail.com

invite sent

2023-09-09 09:56 UTC, DerTimonius commented
sorry for the stupid question, but how do I access the comments? can't find them in the notifications in the previews

2023-09-09 10:42 UTC, is-it-ayush commented
> sorry for the stupid question, but how do I access the comments? can't find them in the notifications in the previews

Select "8 unresolved"  from https://github.com/typehero/typehero/pull/594#issuecomment-1704355021 in the "typehero-web-staging" row.
![image](https://github.com/typehero/typehero/assets/36449128/5c760715-afc3-4367-bca4-837f0cc3660e)

2023-09-09 15:55 UTC, bautistaaa commented
> > sorry for the stupid question, but how do I access the comments? can't find them in the notifications in the previews
> 
> Select "8 unresolved" from [#594 (comment)](https://github.com/typehero/typehero/pull/594#issuecomment-1704355021) in the "typehero-web-staging" row. ![image](https://user-images.githubusercontent.com/36449128/266775641-5c760715-afc3-4367-bca4-837f0cc3660e.png)

click visit preview next to that and login

you should see a toolbar bottom middle like his 

<img width="894" alt="CleanShot 2023-09-09 at 08 54 45@2x" src="https://github.com/typehero/typehero/assets/3660667/2ad58771-1909-4fae-9445-4321d9ef5a34">

2023-09-13 05:24 UTC, bautistaaa commented
pulse check on this to see if this PR is still alive

2023-09-13 07:35 UTC, DerTimonius commented
yes, still alive. struggling to find a good background (not my expertise tbh)

2023-09-14 15:21 UTC, bautistaaa commented
> yes, still alive. struggling to find a good background (not my expertise tbh) help with that is much appreciated!

its okay this doesnt need to be 100% done. incremental progress is fine since we arent live yet!

2023-09-14 15:39 UTC, DerTimonius commented
I think other than that I implemented the changes of the comments

2023-09-14 16:01 UTC, bautistaaa commented
> I think other than that I implemented the changes of the comments

awesome let me take a look. theres also a conflict that needs resolving

2023-09-15 13:02 UTC, is-it-ayush commented
![image](https://github.com/typehero/typehero/assets/36449128/aa9824a1-f77f-467f-b94b-2c235159e247)


Quick Thoughts:
-  The page needs to be slightly more detailed. We need to include description for each challenge such that a user can have a quick glance before enrolling/unenrolling on a track.
- Have an alert before enrolling from the track.
- Search tracks?
- Sort tracks

2023-09-15 13:04 UTC, is-it-ayush commented
great work! lgtm 🚀

2023-09-15 13:04 UTC, is-it-ayush approved these changes

2023-09-15 15:38 UTC, merged

2023-09-15 15:38 UTC, is-it-ayush commented
Thank you for the PR @DerTimonius! : D

2023-09-15 16:08 UTC, DerTimonius commented
Thanks for the review and merge!