722 : Change fill color for rect elements on landing page
typehero/typehero pull request #749
Opened 2023-10-02 03:58 UTC by DevWig

## Description
Change fill color for rect elements representing code lines in the sample challenge cards on the landing page to change with the dark and light themes using TailwindCSS

## Related Issue
Issue #722 

## Motivation and Context
The color of the rect elements in the sample challenge cards on the landing page did not update when the theme was changed from light to dark mode
#722 Challenge Card Code Lines Colors

## How Has This Been Tested?
Visual verification with screenshots

## Screenshots/Video (if applicable):
<img width="1053" alt="Screenshot 2023-10-01 at 10 45 13 PM" src="https://github.com/typehero/typehero/assets/56195940/a45e916b-ecd8-4b24-8b98-c60fbd9622e1">
<img width="1052" alt="Screenshot 2023-10-01 at 10 45 47 PM" src="https://github.com/typehero/typehero/assets/56195940/998e220e-5d40-410b-9ee2-833415285fc9">

2023-10-02 04:35 UTC, PickleNik requested changes
great catch on code lines lacking a light mode, but I think these colors  would look better
<img width="325" alt="Screenshot 2023-10-02 at 12 34 26 AM" src="https://github.com/typehero/typehero/assets/31113245/250c0a2d-e149-4790-803e-e6bed531abcd">
<img width="322" alt="Screenshot 2023-10-02 at 12 34 42 AM" src="https://github.com/typehero/typehero/assets/31113245/eff24a97-9265-41ef-818c-af0195478833">

Edit: actually the no-color lines on dark mode are too dim, keep the neutral-600 for those I think

2023-10-02 04:35 UTC, PickleNik commented on apps/web/src/components/landing/hero-challenge-card.tsx
> +            className="fill-neutral-400 dark:fill-neutral-600"
```suggestion
            className="fill-[#ABABb2] dark:fill-[#2B2B32]"
```

2023-10-02 04:35 UTC, PickleNik commented on apps/web/src/components/landing/hero-challenge-card.tsx
> +            className="fill-blue-500 dark:fill-blue-500"
```suggestion
            className="fill-[#A48088] dark:fill-[#544048]"
```

2023-10-02 04:35 UTC, PickleNik commented on apps/web/src/components/landing/hero-challenge-card.tsx
> +            className="fill-fuchsia-500 dark:fill-fuchsia-700"
```suggestion
            className="fill-[#A48088] dark:fill-[#544048]"
```

2023-10-02 04:35 UTC, PickleNik commented on apps/web/src/components/landing/hero-challenge-card.tsx
> +            className="fill-fuchsia-500 dark:fill-fuchsia-700"
```suggestion
            className="fill-[#809F94] dark:fill-[#404F54]"
```

2023-10-02 04:35 UTC, PickleNik commented on apps/web/src/components/landing/hero-challenge-card.tsx
> +            className="fill-neutral-400 dark:fill-neutral-600"
```suggestion
            className="fill-[#ABABb2] dark:fill-[#2B2B32]"
```

2023-10-02 04:35 UTC, PickleNik commented on apps/web/src/components/landing/hero-challenge-card.tsx
> +            className="fill-neutral-400 dark:fill-neutral-600"
```suggestion
            className="fill-[#ABABb2] dark:fill-[#2B2B32]"
```

2023-10-02 04:35 UTC, PickleNik commented on apps/web/src/components/landing/hero-challenge-card.tsx
> +            className="fill-blue-500 dark:fill-blue-500"
```suggestion
            className="fill-[#A48088] dark:fill-[#544048]"
```

2023-10-02 04:35 UTC, PickleNik commented on apps/web/src/components/landing/hero-challenge-card.tsx
> +            className="fill-blue-500 dark:fill-blue-500"
```suggestion
            className="fill-[#A48088] dark:fill-[#544048]"
```

2023-10-02 04:35 UTC, PickleNik commented on apps/web/src/components/landing/hero-challenge-card.tsx
> +            className="fill-fuchsia-500 dark:fill-fuchsia-700"
```suggestion
            className="fill-[#809F94] dark:fill-[#404F54]"
```

2023-10-02 04:35 UTC, PickleNik commented on apps/web/src/components/landing/hero-challenge-card.tsx
> +            className="fill-fuchsia-500 dark:fill-fuchsia-700"
```suggestion
            className="fill-[#809F94] dark:fill-[#404F54]"
```

2023-10-02 04:56 UTC, DevWig commented
Requested changes implemented, including the edit to go to a light shade on the dark mode for the no-color lines. I did go with neutral-700 though because neutral-600 looked a bit too light next to the red tinted lines.

2023-10-02 18:16 UTC, QuiiBz approved these changes
Looks good! There is a conflict though, you might want to rebase on main.

2023-10-03 13:50 UTC, PickleNik approved these changes
lgtm

2023-10-03 13:50 UTC, merged